version: '3.1'

services:

        node:
                build : .
                networks: 
                        - front-tier
                deploy: 
                        replicas : 3

        load-balancer:
                image: dockercloud/haproxy:latest
                ports:
                        - 8080:8080
                depends_on:
                        - node
                links:
                        - node
                networks:
                        - front-tier
                volumes:
                        - /var/run/docker.sock:/var/run/docker.sock

networks: 
        front-tier:
                driver: bridge
